name: SecretHub - Export Environment Variables
description: Make secrets from SecretHub available to your job as environment variables
runs:
  using: docker
  image: Dockerfile
branding:
  icon: lock
  color: blue
