on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangchao475/helloword/env-export@mater
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETONE_CREDENTIAL }}
          PASSSECRET: secretone://vin/repo/pass
      - name: Print environment with masked secrets
        run: printenv
