on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./env-export
        env:
          SECRETONE_CREDENTIAL: ${{ secrets.SECRETONE_CREDENTIAL }}
          NAME: secretone://tina/repo/mysql/user
          TEST: thisistest
      - name: Print environment variables
        run: echo "NAME=$TEST"
