on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./env-export
        env:
          SECRETONE_CREDENTIAL: ${{ secrets.SECRETONE_CREDENTIAL }}
          PASSSECRET: secretone://tina/repo/mysql/user
      - name: Print environment with masked secrets
        run: printenv
